### ISSUE TITLE
[External - Prism.DryIoc.Extensions] Authenticationhandler can only work on the last registered item？？？

### ISSUE THREAD

**Issue by dorisoy** [Respawnsive/Apizr#3]
**I have defined three interfaces, as follows:**

 [Policy("TransientHttpError")]
    [WebApi(GlobalSettings.BaseEndpoint + "api/v3/dcms/news", isAutoRegistrable: false), Trace]
    public interface INewsApi
    {
        [Get("/topnews/0/6")]
        [Headers("Authorization: Bearer")]
        Task<APIResult<IList<NewsInfoModel>>> GetTopNewsAsync([CacheKey] int storeId, CancellationToken calToken = default);
    }

   [WebApi(GlobalSettings.BaseEndpoint + "api/v3/dcms/auth/user", isAutoRegistrable: false), Trace]
    public interface IAuthorizationApi
    {
        [Get("/bearer/{store}/{userid}")]
        [Headers("Authorization: Bearer")]
        Task<HttpResponseMessage> AuthBearerAsync(int store, int userid);
    }

**Register as follows in   Startup : PrismStartup**

//（1）
services.UseApizrFor<INewsApi>(ob => ob
            .WithHttpTracing(HttpTracer.HttpMessageParts.All)
            .WithCacheHandler<AkavacheCacheHandler>()
            .WithAuthenticationHandler<IAppSettings>(settings => settings.Token, OnRefreshToken));

//（2）
 services.UseApizrFor<IAuthorizationApi>(ob => ob
            .WithHttpTracing(HttpTracer.HttpMessageParts.All)
            .WithCacheHandler<AkavacheCacheHandler>()
            .WithAuthenticationHandler<IAppSettings>(settings => settings.Token, OnRefreshToken));

**Test case as follows:**

//Test
 var newsServie = Shiny.ShinyHost.Resolve<IApizrManager<INewsApi>>();
 var news = await newsServie.ExecuteAsync((ct, api) => api.GetTopNewsAsync(Settings.StoreId, ct), CancellationToken.None);
// 401  Unauthorized！！

var _httpBinManager = Shiny.ShinyHost.Resolve<IApizrManager<IAuthorizationApi>>();
var response = await _httpBinManager?.ExecuteAsync(api => api.AuthBearerAsync(Settings.StoreId, Settings.UserId)) as HttpResponseMessage;
// 200 Ok！！

**When I change the order of 1 and 2, the 1 available request succeeds and 2 fails**

//Test
 var newsServie = Shiny.ShinyHost.Resolve<IApizrManager<INewsApi>>();
 var news = await newsServie.ExecuteAsync((ct, api) => api.GetTopNewsAsync(Settings.StoreId, ct), CancellationToken.None);
// 200 Ok！！

var _httpBinManager = Shiny.ShinyHost.Resolve<IApizrManager<IAuthorizationApi>>();
var response = await _httpBinManager?.ExecuteAsync(api => api.AuthBearerAsync(Settings.StoreId, Settings.UserId)) as HttpResponseMessage;
// 401  Unauthorized！！

**？？？？？ I need your help. Thank you very much！！！**

**Comment by JeremyBP** [comment]
Hi @dorisoy ,

Actually, I noticed that behavior yesterday on my side.
Thank you for reporting it.
I have to fix that thing.

Expect a 1.5.1 nuget update probably tomorrow.

Regards

**Comment by JeremyBP** [comment]
Ok I investigated.

First I tried to reproduce this bug in the mobile sample with two authenticated api interfaces.
Same config as yours, same error 401 as yours.
Then I tried with the console sample with all the same config but not the same result, as it returned me a success 200 for both api calls...?!!!

I found out that I was using MS DI with the console sample and DryIoc with the mobile one.
And guess what? Replacing DryIoc by MS DI in the mobile sample fixed the problem.

Actually, we're still talking about the same problem wich is #1, wich still comes from [#124](https://github.com/dansiegel/Prism.Container.Extensions/issues/124) on Prism.DryIoc.Extensions

Apizr makes use of AddHttpClient and AddTypedClient service collection official extensions wich register multiple implementation type for a same service type. This is not yet available using Prism.DryIoc.Extensions. That's what I'm talking about on my Readme notes.

Personally, my workaround is to use Prism.Microsoft.DependencyInjection.Extensions instead of Prism.DryIoc.Extensions. 

Actually, waiting for this to be fixed and released on Nuget for DryIoc, you'd better download the [Prism.Container.Extensions](https://github.com/dansiegel/Prism.Container.Extensions) project as I did, fixe the MS DI NavigationService [issue](https://github.com/dansiegel/Prism.Container.Extensions/issues/113) like I did in this not yet approved [PR](https://github.com/Respawnsive/Prism.Container.Extensions/commit/38772c2c47bb25699978e7ee4f15eff818ffc581) (only one line of code), and refrence this MS DI project directly into yours.

You'll get all working as excpected so far.

**Comment by dorisoy** [comment]
@JeremyBP 
Well, as you said, Thank you for your contribution to this project and I will adopt the solution you suggest。

**Comment by JeremyBP** [comment]
Dan just pushed its container extensions packages on NuGet with multiple instance registration/resolution feature, witch finally fix this. Please make sur to update to at least v8.0.48

**Comment by dorisoy** [comment]
> Dan just pushed its container extensions packages on NuGet with multiple instance registration/resolution feature, witch finally fix this. Please make sur to update to at least v8.0.48

@JeremyBP   Thank you for sharing everything for open source !
